### ISSUE TITLE
Clarify relation to jxrlib.codeplex.com

### ISSUE THREAD

**Issue by mloskot** [glencoesoftware/jxrlib#16]
Please, consider adding a basic README file and clarify what is the relation, if any, between 
https://github.com/glencoesoftware/jxrlib/ and http://jxrlib.codeplex.com/

Thanks!

Is the former a fork with aim of active maintenance, development of a good C++ wrapper, etc.?

**Comment by alexsavio** [comment]
http://blog.openmicroscopy.org/file-formats/community/2016/08/31/bf-partnerships/

**Comment by mloskot** [comment]
@alexsavio Thanks for the update on that issue. 

Perhaps a note based on this could go in README

> partnership has been established with Glencoe Software to add a Java-based JPEG-XR decoder to Bio-Formats. Thanks to extensive, fruitful discussions with ZEISS all outputs of this partnership are publicly available and all source code licensed identically to other OME projects
