### ISSUE TITLE
Undefined behavior in print_bytes

### ISSUE THREAD

**Issue by phuclv90** [glencoesoftware/jxrlib#23]
`bytes[i++], bytes[i++], bytes[i++], bytes[i++]` invokes UB because i was modified between 2 sequence points

```cpp
static void print_bytes(std::vector<char>bytes, std::FILE *out = stderr) {
  for (int i = 0 ; i < bytes.size() ; ){
    fprintf(out, "0x%.2x%.2x%.2x%.2x%c", bytes[i++], bytes[i++], bytes[i++], bytes[i++],
            i % 40 == 0 ? '\n' : ' ');
  }
}

static void print_bytes(std::vector<unsigned char>bytes, std::FILE *out = stderr) {
  for (int i = 0 ; i < bytes.size() ; ){
    fprintf(out, "0x%.2x%.2x%.2x%.2x%c", bytes[i++], bytes[i++], bytes[i++], bytes[i++],
            i % 40 == 0 ? '\n' : ' ');
  }
}
```

https://github.com/glencoesoftware/jxrlib/blob/ab7035615f851705a0ffb028eac76f22ae445f0d/cpp/jxrdecode.cpp#L59

- [Why are these constructs using pre and post-increment undefined behavior?](https://stackoverflow.com/q/949433/995714)
- [Undefined behavior and sequence points](https://stackoverflow.com/q/4176328/995714)
- [Post/pre increments in 'printf'](https://stackoverflow.com/q/4706404/995714)

**Comment by melissalinkert** [comment]
Thanks for catching this, @phuclv90.  Both methods were only intended for internal debugging and are no longer used.  #24 proposes to remove both entirely.

**Comment by chris-allan** [comment]
Closing with the merge of #24 removing the use of these constructs entirely.
